dataset_name: 'retina'
dataset_path: '$CUTS_ROOT/data/retina/'
model_save_path: '$CUTS_ROOT/checkpoints/retina.pty'
output_save_path: '$CUTS_ROOT/results/retina/'
log_folder: '$CUTS_ROOT/logs'
model_setting: 'full' # 'full', 'no_recon', 'no_contrastive'
learning_rate: 5e-3
weight_decay: 1e-4
max_epochs: 200
patience: 10
batch_size: 16
num_kernels: 16
sampled_patches_per_image: 16 # recommend: 4 or above.
num_workers: 8
lambda_contrastive_loss: 1
lambda_recon_loss: 10
random_seed: 1
train_val_ratio: '8:1'
pos_enc_gamma: 0.0
segmentation_paradigm: 'kmeans_point'
test_metric: None
