dataset_name: 'retina'
dataset_path: '$CUTS_ROOT/data/retina/'
supervised_network: 'unet'
model_save_path: '$CUTS_ROOT/checkpoints/supervised_retina_unet_seed2022.pty'
output_save_path: '$CUTS_ROOT/results/retina_seed2022/'
log_folder: '$CUTS_ROOT/logs'
learning_rate: 1e-3
weight_decay: 1e-4
max_epochs: 200
patience: 10
batch_size: 16
num_kernels: 16
num_workers: 8
random_seed: 2022
train_val_test_ratio: '7:1:2'
pretrained: False